### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by melMass** [scott-wilson/alembic-rs#1]
Hello what is this please?
I'm trying to do an Alembic crate myself and discovered this on crates.io

Thanks

**Comment by scott-wilson** [comment]
I should probably archive this repo, but I highly recommend that you check out the Academy Software Foundation Working Group (https://github.com/vfx-rs/organization). We're working on creating Rust bindings of the packages we use and love in the VFX industry, with the goal of making those Rust bindings the official Rust bindings of those projects.

If you want to join us, feel free to join the ASWF Slack and bi-weekly meetings. I don't think we have a maintainer for the Alembic bindings at the moment, but we could give you that role if it interests you.

**Comment by melMass** [comment]
> I highly recommend that you check out the Academy Software Foundation Working Group

I did and actually found other empty "template" repos to be handed over.

> If you want to join us, feel free to join the ASWF Slack and bi-weekly meetings. 

Starting from next week or the one after I would love to, is there something to do to join the slack? Last time I tried to access the ASWF Slack I could not connect (not a Slack expert here 😅 ).

> I don't think we have a maintainer for the Alembic bindings at the moment, but we could give you that role if it interests you.

Not sure about being the main maintainer but I would love to help for sure!

Thanks this is exciting!

**Comment by scott-wilson** [comment]
I see that you're now on the Slack channel. I'll close this issue.
